### ISSUE TITLE
[Feature]: Hi.  <createUpdateMetadataAccountV2Instruction >  not working for pNfts.

### ISSUE THREAD

**Issue by happyday03518** [metaplex-foundation/metaplex-program-library#1038]
### Which package is this feature request for?

token-metadata

### Feature

Hi. Thank you to your contribute to crypto world.
I opened ticket for simple change.
I made some apps that using createUpdateMetadataAccountV2Instruction from @metaplex-foundation/mpl-token-metadata.
It works well with nfts but pNfts.
When I trying it with pNfts. it returns 0x99 error from transaction.
I made query about it to metaplex comunity and they replied it is requireing SDK update.
Please check this and gimme solution.
I really need your urgent help.
Thank you.

### Standard Change?

No

### Ideal solution or implementation

I want createUpdateMetadataAccountV2Instruction from @metaplex-foundation/mpl-token-metadata  works for nNfts

**Comment by lorisleiva** [comment]
Hi there,

When introducing PNFTs, we introduced a brand new set of instructions that support both PNFTs and regular NFTs (as well as all other standards).

Thus, in order to update PNFTs, you must use [the new `Update` instruction](https://github.com/metaplex-foundation/metaplex-program-library/blob/042d6204114cb3b1914548b998d4ff261e220767/token-metadata/js/src/generated/instructions/Update.ts).

`UpdateMetadataAccountV2` was purposefully left unchanged for backwards compatibility.
