### ISSUE TITLE
Can/Should the Candy Machine be invoked using CPI?

### ISSUE THREAD

**Issue by EPNW** [metaplex-foundation/metaplex-program-library#138]
First a bit of background to better understand my request. Please correct me if my statements are not correct (since I'm still learning).

I wanted to create my own NFT on Solana. Since I have an Ethereum background I made the assumption that the process is not that different, but there seems to be a core difference tough:
* On Ethereum, NFTs are lazily mindet, meaning that I implement a mint method in an ERC721 compatible smart contract, and if this is called by a customer, the NFT is created (in most cases as entry in a solidity `mapping`).
* On Solana, most NFTs seem to be created in advance or at least not by a seller written program, but are created using the CLI. The NFT mint account than exists and is then used to later mint to a customers token account if the NFT is "bought".

On Solana, we need additional accounts for a mint account to be recognized as NFT by marketplaces, namly a Metadata Account and a MasterEdition Account. Both of these accounts are owned (and the standard defined) by the Metaplex Token Metadata Program, where as the Mint Account and Token Account are owned by the System Token Program.

So in order to mint lazily on Solana, I could write a on-chain Program that lazily creates these three accounts. Then I dont have to pay up front for the account creation, but can create the accounts just in time when a customer buys my NFT. (Sure I could do this with an off-chain server invoking the CLI lazily but that would not be decentralized)

Now I have some security fears implementing this myself, but the Candy Machine is already out there doing all this account creation in a presumably safe and security audited way. The Candy Machine is just another on-chain Program so my idea is now writing an own Program that does some validating and than calls the Candy Machine via CPI. Is this possible/a good idea? Is the Candy Machine an upgradable Program or can I be sure it's on-chain implementation won't change? Whats the Program address of the Candy Machine?

**Comment by roederw** [comment]
You've inspired me to do a 2022 write up (that will also explain the difference between ETH and Solana).

The quick dirty explanation is that, in the Solana world, NFT data (on the Metaplex Standard) is represented in a PDA which is created using the seed of a `Mint Account`. When you open an NFT on the Solana Explorer ([see this example](https://explorer.solana.com/address/JAKTkNWAhGLKxTpmftkxW3DLUmmjw5sS7d98y7Brvxs)) you're actually looking at the `Mint Account` that represents the NFT information. This `Mint Account` is identical to a `Mint Account` associated with a `Fungible Token` ([see USDC](https://solscan.io/token/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v)).

A key thing to understand, is that just because a `Mint Account` is created for a Token `Fungible or Non-Fungible` it does not mean anyone has "minted" it. The `Mint Authority` will mint the token (using the `Mint Account`) and send it to the new owner, after creating a ATA (`Associated Token Account`). This links that `Mint Account` data to the owner of the newly minted token.

I'm going to try and formulate this explanation a bit better in a formal write up. Please let me know if anything is fuzzy.

**Comment by EPNW** [comment]
Thanks for the ansewer! I'm really looking forward to a write up :) It seems that most resources out there are about how to use the candy machine, but I would really love to understand how it works internally.

For this I started digging in the code (as you said, it's open source). I want to post my findings and tought process here, since I hope it could point out some aspects that bugged me at first and could be included in the write up.

I've read  https://github.com/metaplex-foundation/metaplex/blob/21ec68efb411b03846f260e30b56d67aefa0d7f3/js/packages/candy-machine-ui/src/candy-machine.ts and assume this code runs client side. The following instructions are executed, in this order:

```
anchor.web3.SystemProgram.createAccount
Token.createInitMintInstruction
createAssociatedTokenAccountInstruction
Token.createMintToInstruction
Token.createApproveInstruction
candyMachine.program.instruction.mintNft
```

The way I understand this is that the last instruction mints the NFT using the candy machine and gets a Mint Account (created using instructions 1 and 2) and an Associated Token Account (created in instruction 3), which already holds a token from the Mint Account (due to instruction 4), as parameters.

First I asked myself: Why is it ok that all these accounts are created not by the candy machine (the on chain program) but by the buyer? I than realized that just a Mint Account and a Token Account are "worthless" without Token Metadata to identify it as a NFT belonging to a certain collection (I now also understand why the Token Standard 1.1.0 introduces the collection field I guess). So it's totally fine if the accounts are not created by the candy machine, as it can just deny adding Metadata if something does not seem right.

I noticed that in the candy machine code, there is no check if the supply of the Mint Account is 1. This bugged me at first, since it would mean there is no check that if in instruction 4 the buyer only mints one token. This issue got solved when looking at the code that creates the master edtion in the Metaplex Token Metadata Program, since it is checked there.

Maybe an additional question here: In the text above, when I mentioned the candy machine, I always referred to only the on-chain program. Is this correct? Or are the instructions that are not issued by the on-chain program but by the buyer here also considered part of the candy machine?
