### ISSUE TITLE
Whole Collection Fetching

### ISSUE THREAD

**Issue by aheckmann** [metaplex-foundation/metaplex-program-library#154]
Due to Prior Data structure additions e.g. `nonce` in the Token Metadata data structure, the location of the Collection is not ideal.
This task is meant to provide stop-gap solution until Solana 1.9 comes out with resizable accounts.

**Comment by kevinfaveri** [comment]
+1 to this. Do you have any implementation ideas of how this would work (and RFC maybe where we could discuss product and implementation details in your mind)? Maybe I can help to code it @austbot :)

I feel like the current solution  (getProgramAccounts) is nondeterministic because of the optional field in the struct that comes right before the collection field and also it is not performative since we might need to do multiple calls to get a hash list of a collection :/

**Comment by roederw** [comment]
@kevinfaveri I'm going to try and get you guys something this week.

**Comment by samuelvanderwaal** [comment]
https://www.notion.so/metaplex/Get-Collection-Methods-1ff0b118e4ce4605971df60e753a8559
