### ISSUE TITLE
Collection Field in the Metadata Struct

### ISSUE THREAD

**Issue by RajaAli420** [metaplex-foundation/metaplex-program-library#180]
For the new standard the collection has got me confused and from the documentation it's pretty clear that the collection will have the address of the SPL Token(NFT)!
https://docs.metaplex.com/token-metadata/v1.1.0/specification
but then when we read a bit more in to it, it says:

"Possible to find all NFTs that belong to a given collection by making a getProgramAccounts call"
"Uses existing padding at the end of Metadata so adds no on-chain rent storage costs"

If you say collection will have the address for each minted token, then how does that make it easy to find all NFTs or do you guys mean that we can find the metadata accounts and from there the verified collection(NFT)!  Having different addresses wouldn't be helping us out in memcp filter search for the getProgramAccounts.. having a better explanation on it would be much better for us!

Also a collection is a single NFT as stated in the docs or a collective collection for all NFT saying this because 
"A collection is an NFT. It has the same data layout on-chain as any other NFT." in the link given above!

**Comment by vpontis** [comment]
I found this in another issue: https://metaplex.notion.site/Get-Collection-Methods-1ff0b118e4ce4605971df60e753a8559

It seems like not allowing `getProgramAccounts` to find all of the NFTs in a collection was a big oversight. [I have a proposal for improving the NFT standard](https://lu.ma/p/CM0oovlwagtYho6/Proposal-New-Solana-NFT-Spec) that I hope Metaplex adopts.

**Comment by samuelvanderwaal** [comment]
It's possible to use a getProgramAccounts call or calls to find all the collections data if you know a priori what the offset will be but it's admittedly not a great solution. In the link Victor posted above I discuss this and an alternative method for getting all collection NFTs: https://metaplex.notion.site/Get-Collection-Methods-1ff0b118e4ce4605971df60e753a8559. 

I also take to heart that our docs need to be updated and clarified and have put together a document with notes for our team to work on docs updates. 

> It seems like not allowing getProgramAccounts to find all of the NFTs in a collection was a big oversight.

Adding changes to an existing standard is complicated and there are a lot of trade-offs involved. In general, `getProgramAccounts` is something the community needs to move away from as it doesn't scale well for programs that own a lot of accounts. A number of RPCs now actively block this call for the `token-metadata` program because it's too resource intensive on their machines. This will be the case for any program that ends up owning a lot of accounts. The long term solution to this is probably indexing.
