### ISSUE TITLE
[Feature]: Add custom program error 0x3B (DataIsInmutable) to verify_collection and related instructions when the Metadata Account has is_mutable flag set to false

### ISSUE THREAD

**Issue by bletelier** [metaplex-foundation/metaplex-program-library#744]
### Which package is this feature request for?

token-metadata

### Feature

When someone tries to `verify_collection` on a Metadata Account that has `is_mutable` the following error is returned `<MY_AUTH_PUBKEY>'s  writable privilege escalated`, everything was correctly set on the program, except for the not mutable metadata account. This error is not easy to debug so it would be great to have error 0x3B reported instead.

### Standard Change?

No

### Ideal solution or implementation

Create a new assertion function that helps checking if the `is_mutable` flag is set to false and someone is trying to update/set/verify some field on the Metadata account, if is set to false return error 0x3B. Then, add the new assertion in the respective instructions that change Metadata account information.

**Comment by samuelvanderwaal** [comment]
Is the issue that the *account* was passed in as immutable instead of mutable or that a mutable metadata account was passed in but the `is_mutable` flag was set on the metadata account? Collection verification isn't affected by the `is_mutable` flag as that only protects the inner data struct. This sounds like an issue of the actual metadata account being passed in as immutable when it needs to be mutable to be updated.
