### ISSUE TITLE
[Feature]: Per wallet minting limiation for candy-machine

### ISSUE THREAD

**Issue by calldata** [metaplex-foundation/metaplex-program-library#761]
### Which package is this feature request for?

candy-machine

### Feature

Currently there is no limiation for how many NFTs one wallet can mint in candy-machine. When on public sale, it's reasonable to have such limiation for "fair" .

### Standard Change?

No

### Ideal solution or implementation

Add additional config for candy-machine.

**Comment by samuelvanderwaal** [comment]
You can actually do this by using whitelist tokens and the BurnEveryTime mode, then you just airdrop the appropriate number of whitelist tokens to each wallet. For more details check out the [Sugar documentation](https://docs.metaplex.com/developer-tools/sugar/learning/settings#whitelist-settings).

Otherwise, Candy Machine V2 is approaching end-of-life and we are not going to be adding new features to it, but stay tuned for the next iteration which brings more flexibility to NFT minting.
