### ISSUE TITLE
Execute_Sale(remaining_accounts) issue on NFT that is minted through CM/Sugar

### ISSUE THREAD

**Issue by samia-invozone** [metaplex-foundation/metaplex-program-library#852]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

Hi, I'm trying to run execute instruction using Auctioneer with NFT that has been minted through candy machine or sugar etc;

But actually, it looks like the auction house smart contract seems not to be compatible with these types of collections because creator on index 0 is candy machine address and when I try to pass these addresses into remaining accounts it returns an error of "An account required by the instruction is missing”.  Here is the NFT for which i'm trying to run execute rpc call with remaining accounts. https://solscan.io/token/78sJUf27U45coCt1HzPMAdQKRLWWee46CfRTaRRZgASk?cluster=devnet#metadata

Following are the successful transactions for listing & bidding:

https://solscan.io/tx/5xkp1DFpKqLq2fkLM9MYFCLQdqDf9TMEhrXkuyGkzH84Fyjf92XMztfyi9VDpxJEj4ZDxPvgMPqKSCiuJhvtjvYj?cluster=devnet

https://solscan.io/tx/2niP4SNtB5xWSkaMoBaqi7e2y1i8P2kkq1DaBHh6gpMBdwk84FkAuSWRVD8h3Vgfez8Chtz9P87fVnomnYUQo8Um?cluster=devnet

Using following code for sending remaining accounts:

` .remainingAccounts([
        {
          pubkey: new PublicKey("5k2EPeEp4ZZaRKdW7uDvTxwoRgYkatk15LEhRPYXhaxD"),
          isWritable: false,
          isSigner: false,
        },
        {
          pubkey: new PublicKey("4douvideaZJtZLztHJK8H5FDrr1AkVYZUWGDgyYxCwL8"),
          isWritable: true,
          isSigner: false,
        },
      ])`

### Relevant log output

```shell
logs
: 
Array(5)
0
: 
"Program neer8g6yJq2mQM6KbnViEDAD4gr3gRZyMMf4F2p3MEh invoke [1]"
1
: 
"Program log: Instruction: ExecuteSale"
2
: 
"Instruction references an unknown account 5k2EPeEp4ZZaRKdW7uDvTxwoRgYkatk15LEhRPYXhaxD"
3
: 
"Program neer8g6yJq2mQM6KbnViEDAD4gr3gRZyMMf4F2p3MEh consumed 70441 of 200000 compute units"
4
: 
"Program neer8g6yJq2mQM6KbnViEDAD4gr3gRZyMMf4F2p3MEh failed: An account required by the instruction is missing"
length
: 
5
[[Prototype]]
: 
Array(0)
programErrorStack
: 
wt {stack: Array(1)}
message
: 
"failed to send transaction: Transaction simulation failed: Error processing Instruction 0: An account required by the instruction is missing"
```

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
Is this on `mainnet` or `devnet`? The account `5k2EPeEp4ZZaRKdW7uDvTxwoRgYkatk15LEhRPYXhaxD` account does not exist on `mainnet`.

**Comment by samia-invozone** [comment]
@samuelvanderwaal This is on devnet

**Comment by KartikSoneji** [comment]
I can replicate the issue on mainnet.
The issue seems to be with sales where the nft creators are only present in `remaining_accounts`.

Here's a simulation for `Execute` for a creator that's not the same as one of the named accounts:
[explorer link](https://explorer.solana.com/tx/inspector?signatures=%255B%25221111111111111111111111111111111111111111111111111111111111111111%2522%255D&message=AQAOGpi26pK7e%252FHvjc5gjtmvRYNjyzPRtT6P3lzU08na9sQ8OA%252FpaftAOsmQwaaZAeNcHvLuQz6C2UcXpHcCcKQNdZ9QdwDDQuyieYorcv2x%252B7cY5Q8rjwbYpsa5nt1lgISB1IMgpdeNkUZTXyvU7lBs7BLXp%252FT6XcKctTsv5hmyNVxfnbavCm%252BgrOdPCUmqyamJTnkih6ClFOsADdDRwlFvrG6hb7q9x9Lkajh0S%252B%252FePrHlYC0%252FSJh0Vl2YfXXE1othC68Z8KTI0B60lrgqsw7%252FVKs8s7OPJ4N73nqhn8PtdYnrvWvuXiiyPeV1hvfGYwf%252F3mXkH8mypNB6W4yYSDgO9Ui97J5dU7TeUl6G2nDwxbMot58qg16%252FXFTJ7KqrQcuC%252FMKjZChWJ1lrjs7vrI4oOMFpj2ZD59tdPY5VaNkg8fogx73P4SGOpq24xysmgJsXYbNyb8mLzxx94yUwLAClSNLQJ1vr%252BV8HrUW%252FQ9r3SmuJyMOP2SuPXS5wEfguvid4FgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK1Ueu1WHKuJsycJ%252FhX%252B3cx1P%252FJElJgB11zuH9gOT%252Brta%252BYI8AkLIGMG0rKtw0VGO0iHSpi1aFFmAOuS2YI0J0GKZ1EwQOvG%252BkR15IDyTVZhpXuXxKV84FLf9NHwr7Ki4aIS%252FC6xkl0YlLwh5GX8ma5ZIqPpbNfMqNdSLgA74RwCMlyWPTiSJ8bs9ECkUjg2DC1oTmdr%252FEIQEjnvY2%252Bn4WbFX73meNDWdfhOqq4eAb2xDGD9lYJTIcD1xMyWe9dLs3WKQ0ES4jAH%252F0wifcdLPdcKDn8tIC8NDP4L2hPN4BREKZZOGPLpGFWTq5BNzchVG6wFRyTCCdrvUrSocOkIQe%252FQkXpd1kxJfsVlBtsCpJgr0Q4vNEDVSkqQLBd%252BH9dUgC7G11A5PqKy17Zlh8hNRxKIWhRnM%252BxbAvpYmRllpzsoGm4hX%252FquBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAQan1RcZLFxRIYzJTD1K8X9Y2u4Im6H9ROPb2YoAAAAABt324ddloZPZy%252BFGzut5rBy0he1fWzeROoz1hX7%252FAKma3ZAdBftKfrlfW6gn7zFoj9jcAYHi7iMNm6%252FHJbNFwQEWGhQJAwAIDg8XCwAFExAECgIHAQ0SGQwRFRgGHCVK2Z1PMSMG%252Ff%252F%252F%252FgDC6wsAAAAAAQAAAAAAAAA%253D)

Here's the link to the nft: https://explorer.solana.com/address/788MrdsXbgqC2yGijKXaVuddxaQY3tRvqeNcn1WaSzrT
